repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ['-r', 'src/']
        exclude: tests/

  - repo: local
    hooks:
      - id: check-credentials
        name: Check for credentials
        entry: bash -c 'if grep -r "password.*=" --include="*.py" --include="*.json" --include="*.yaml" .; then echo "Found potential credentials in code"; exit 1; fi'
        language: system
        pass_filenames: false